version: 2
updates:
  # Update to newer version of GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "nuget" # for fable and test frameworks
    directory: "./Test/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7


