name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6.0.3

      - name: Setup .NET
        uses: actions/setup-dotnet@v5.3.0
        with:
           dotnet-version: '10.x'

      - name: Run F# Tests1
        run: dotnet test Test/FSharp/Tests/Tests1/Tests1.fsproj

      - name: Run F# Tests2
        run: dotnet test Test/FSharp/Tests/Tests2/TestsZ.fsproj

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24.x'

      - name: Clean Install npm dependencies
        working-directory: ./Test
        run: npm ci

      - name: Build JS tests
        working-directory: ./Test
        run: npm run build

      - name: Run tests JS
        working-directory: ./Test
        run: npm test
